[build] 
  publish = "dist"
  command = "npm run build"

[dev] 
  publish = "dist"
  command = "npm run serve"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[[redirects]]
  from = "/ideas/*"
  to = "/.netlify/functions/view-idea/:splat"
  status = 200
